apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
#  namespace: my-namespace
spec:
  replicas: {{ .Values.app.replicas }} 
  selector:
    matchLabels:
      components:  {{ .Values.app.components }}
  template:
    metadata:
      labels:
        components:  {{ .Values.app.components }}
    #lables - может быть любым, даже test: pepepe
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image }}:{{ .Values.app.version }}"
          ports: 
            - containerPort: {{ .Values.app.port }}
          resources:
            limits: {{ .Values.app.limits | toYaml | nindent 14 }}
            requests: {{ .Values.app.requests | toYaml | nindent 14 }}
# toYaml - переводит в ямл
# nintent - добовляет отступы. Самим нужно посчитать сколько нужно считаем внутренюю структуру)
# helm install --debug --dry-run sort-service-release ./short-service - строка проверки до запуска