apiVersion: v1
kind: Secret
metadata:
  name: short-api-secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL2RlbW86ZGVtb0Bwb3N0Z2VzLWRiY2x1c3RlcmlwOjU0MzIvZGVtbw==


# postgresql://user:password@url:port/database - Вид строки подключения
# url - можно взять из сервиса, так как обращение к сервису по его умени возвращает путь до контейнера
# postgresql://demo:demo@postges-dbclusterip:5432/demo